FROM node:20-bookworm-slim

WORKDIR /app

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN apt-get update -y && apt-get install -y --no-install-recommends openssl \
  && rm -rf /var/lib/apt/lists/*

RUN corepack enable

# Install deps first for better layer caching
COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma

RUN pnpm install
RUN pnpm prisma generate

EXPOSE 4000

CMD ["pnpm", "dev"]
