/**
 * Phase 3: Signal Generation Framework - Type Definitions
 *
 * Core types for pluggable signal generators that create trading alerts
 * based on market movements, competitor relationships, and factor exposures.
 */

import { SignalType, SignalSeverity } from '../../../types/edgar.types.js';
import { FactorType } from '../../../types/document.types.js';

/**
 * Context passed to signal generators during computation runs
 */
export interface GeneratorContext {
  /** Timestamp of current computation run */
  currentTime: Date;

  /** How far back to look for signals to propagate (ms) */
  lookbackWindowMs: number;
}

/**
 * Signal generated by a generator, before database persistence
 */
export interface GeneratedSignal {
  /** Target instrument for this signal */
  instrumentId: string;

  /** Type of signal (PEER_IMPACT, FACTOR_EXPOSURE_ALERT, etc.) */
  signalType: SignalType;

  /** Severity level */
  severity: SignalSeverity;

  /** Numeric score (0-100) */
  score: number;

  /** Confidence in signal validity (0-1) */
  confidence: number;

  /** Human-readable explanation */
  reason: string;

  /** Structured evidence supporting this signal */
  evidenceFacts: EvidenceFact[];

  /** When this signal expires and should be removed */
  expiresAt: Date;
}

/**
 * Base structure for all evidence types
 */
export interface EvidenceFact {
  type: string;
  [key: string]: unknown;
}

/**
 * Evidence: Peer company had significant price movement
 */
export interface PeerPriceMovementEvidence extends EvidenceFact {
  type: 'PEER_PRICE_MOVEMENT';

  /** ID of the peer instrument that moved */
  peerInstrumentId: string;

  /** Symbol/ticker of peer */
  peerSymbol: string;

  /** Price change percentage (e.g., -7.5 for 7.5% drop) */
  priceChangePct: number;

  /** Strength of competitor relationship (0-1) */
  correlationStrength: number;
}

/**
 * Evidence: Correlated factor had significant movement
 */
export interface FactorMovementEvidence extends EvidenceFact {
  type: 'FACTOR_MOVEMENT';

  /** Type of factor (COMMODITY_GOLD, INDEX_SPX, etc.) */
  factorType: FactorType;

  /** Factor price change percentage */
  factorChangePct: number;

  /** Magnitude of exposure (0-1) */
  exposureMagnitude: number;

  /** Direction of exposure (POSITIVE, NEGATIVE, INVERSE) */
  exposureDirection: string;
}

/**
 * Evidence: Signal propagated from related company
 */
export interface PropagatedSignalEvidence extends EvidenceFact {
  type: 'PROPAGATED_SIGNAL';

  /** ID of the source signal being propagated */
  sourceSignalId: string;

  /** Instrument that originated the signal */
  sourceInstrumentId: string;

  /** Type of signal being propagated */
  sourceSignalType: SignalType;

  /** Original confidence before propagation decay */
  originalConfidence: number;
}

/**
 * Statistics for a single generator run
 */
export interface GeneratorStats {
  /** Name of the generator */
  generatorName: string;

  /** Number of signals generated */
  signalsGenerated: number;

  /** Number of instruments processed */
  instrumentsProcessed: number;

  /** Number of errors encountered */
  errors: number;

  /** Signals filtered out due to low confidence */
  skippedLowConfidence: number;
}

/**
 * Statistics for entire computation job
 */
export interface ComputationJobStats {
  /** Total signals generated across all generators */
  totalSignalsGenerated: number;

  /** Total instruments processed */
  totalInstrumentsProcessed: number;

  /** Total errors across all generators */
  totalErrors: number;

  /** Per-generator breakdown */
  generatorStats: GeneratorStats[];

  /** Job duration in milliseconds */
  durationMs: number;
}

/**
 * Price snapshot for tracking changes
 */
export interface PriceSnapshot {
  /** Current price value */
  value: number;

  /** When this price was recorded */
  timestamp: Date;
}

/**
 * Factor price data
 */
export interface FactorPrice {
  /** Factor type identifier */
  factorType: FactorType;

  /** Current price */
  price: number;

  /** Last updated timestamp */
  timestamp: Date;
}
